#SETUP
title: 'rootofpi.me'
email: 'alephalpha0@rootofpi.me'
url: "http://rootofpi.me"
baseurl: "/"
tagline: "Transmissions from space."
description: "Personal website of DK. Blog, Photo Manipulation, Gallery, Coding Fluffery."
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: America/Chicago
strict_front_matter: true

#DEPENDENCIES
markdown: CommonMark
highlighter: rouge

#PERMALINKS
permalink: pretty

#PLUGINS
plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-gallery-generator
  - jekyll-analytics
  - jekyll-timeago
  - jekyll-sitemap
whitelist:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-paginate-v2
  - jekyll-gallery-generator
  - jekyll-analytics
  - jekyll-timeago
  - jekyll-sitemap

#COMMONMARK
commonmark:
  options: ["SMART", "FOOTNOTES", "HARDBREAKS", "LIBERAL_HTML_TAG"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter", "tasklist"]

# GALLERY
gallery:
  dir: photos
  symlink: false
  title: "Digital Optical Traces"
  title_prefix: "gallery: "
  sort_field: "date_time"
  thumbnail_size:
    x: 400
    y: 400

# POST FRONTMATTER DEFAULTS
defaults:
  - 
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
