source "https://rubygems.org"

gem 'jekyll', '4.0.0'
gem 'jekyll-docs'

gem 'jekyll-commonmark', group: [:jekyll_plugins]
gem 'jekyll-feed', group: [:jekyll_plugins]
gem 'jekyll-seo-tag', group: [:jekyll_plugins]
gem 'jekyll-compose', group: [:jekyll_plugins]
gem 'jekyll-paginate-v2', group: [:jekyll_plugins]
gem 'jekyll-analytics', group: [:jekyll_plugins]
gem 'jekyll-timeago', group: [:jekyll_plugins]
gem 'jekyll-sitemap', group: [:jekyll_plugins]
